### ISSUE TITLE
ResAdapter doesn't unload properly

### ISSUE THREAD

**Issue by HaydenReeve** [jiaxiangc/ComfyUI-ResAdapter#16]
ResAdapter does not unload from a workflow once removed or bypassed. It continues to have an affect until you have fully restarted a given instance of ComfyUI.

This makes it quite difficult to create comparisons between On and Off.

If it's not possible to avoid the global-implementation (in contrast to a node-implementation) then perhaps a boolean toggle for On/Off to apply or remove effects on the node would be an alternative solution for the interim.

**Comment by jiaxiangc** [comment]
Thank you for your advice. We will fix this problem later.

**Comment by PrometheusDante** [comment]
That would be greatly appreciated. Not being able to unload it manually is distorting the recreation of previously generated images that turn out differently due to that, preventing fine-tuning with and without the model, unless restarting comfyui repeatedly, which is very inconvenient. Thank you for looking into this.
